apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-master
  template:
    metadata:
      labels:
        app: ansible-master
    spec:
      containers:
      - name: master
        image: kabrajii/ansible_master_setup
        command: [ "sleep", "infinity" ]
