apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ansible-worker
  template:
    metadata:
      labels:
        app: ansible-worker
    spec:
      containers:
      - name: worker
        image: kabrajii/ansible_worker_setup
        ports:
        - containerPort: 22
